config/routes.rb
Rails.application.routes.draw do
  root 'visitors#index'
  get '/about', to: 'visitors#about', as: 'about'
  resources :illustrations
  resources :posts
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  scope :most_recent, -> { order("created_at").last }
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  default_scope -> { order("created_at desc") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  before_action :set_illustration, only: [:show, :edit, :update, :destroy]

  # GET /illustrations
  # GET /illustrations.json
  def index
    @illustrations = Illustration.all
  end

  # GET /illustrations/1
  # GET /illustrations/1.json
  def show
  end

  # GET /illustrations/new
  def new
    @illustration = Illustration.new
  end

  # GET /illustrations/1/edit
  def edit
  end

  # POST /illustrations
  # POST /illustrations.json
  def create
    @illustration = Illustration.new(illustration_params)

    respond_to do |format|
      if @illustration.save
        format.html { redirect_to @illustration, notice: 'Illustration was successfully created.' }
        format.json { render :show, status: :created, location: @illustration }
      else
        format.html { render :new }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /illustrations/1
  # PATCH/PUT /illustrations/1.json
  def update
    respond_to do |format|
      if @illustration.update(illustration_params)
        format.html { redirect_to @illustration, notice: 'Illustration was successfully updated.' }
        format.json { render :show, status: :ok, location: @illustration }
      else
        format.html { render :edit }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /illustrations/1
  # DELETE /illustrations/1.json
  def destroy
    @illustration.destroy
    respond_to do |format|
      format.html { redirect_to illustrations_url, notice: 'Illustration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_illustration
      @illustration = Illustration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def illustration_params
      params.require(:illustration).permit(:title, :image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  require 'home_page_presenter'

  def index
    @posts = Post.all
    @illustrations = Illustration.all
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gimmicks_helper.rb
module GimmicksHelper
  def random_salutation
    ["Hello,", "Salutations,", "Howdy,", "Greetings,", "What's happening?", ].sample.to_s
  end
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/illustrations/_form.html.slim
= bootstrap_form_for(@illustration) do |f|

  .form-inputs
    = f.text_field :title
    = f.file_field :image
    = f.hidden_field :image_cache

  .form-actions
    = f.submit :submit

app/views/illustrations/_illustration.html.slim
.item
  = image_tag illustration.image_url(:medium), href: illustration.image_url

app/views/illustrations/edit.html.slim
h1 Editing illustration

== render 'form'

= link_to 'Show', @illustration
'|
= link_to 'Back', illustrations_path

app/views/illustrations/index.html.slim
.col-md-10
  #grid-container
  #hidden-images
    = render @illustrations

app/views/illustrations/new.html.slim
.container
  .col-md-10
    h1 New illustration

    == render 'form'

    = link_to 'Back', illustrations_path

app/views/illustrations/show.html.slim
p#notice = notice

p
  strong Title:
  = @illustration.title
p
  strong Image:
  = image_tag @illustration.image_url

= link_to 'Edit', edit_illustration_path(@illustration)
'|
= link_to 'Back', illustrations_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Kitcom'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Kitcom'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    link href="http://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet" type="text/css" /
    link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'
    header
      /== render 'layouts/navigation'
    /main[role="main"]
    .logo-container
      = image_tag 'kit_logo.png', height: 125, width: 125, id: "kit-logo"
      = image_tag "loader.png", height: 125, width: 125, id: "spinner"
    .container
      .col-sm-1.link-bar.fade-in
        h2.show-links-button
          span.glyphicon.glyphicon-chevron-down
          span.glyphicon.glyphicon-chevron-up
        .links
          h3.link= link_to_unless_current "HOME", root_path
          h3.link= link_to_unless_current "ART", illustrations_path
          h3.link= link_to_unless_current "ABOUT", about_path
      == render 'layouts/messages'
      == yield

app/views/posts/_form.html.slim
= bootstrap_form_for(@post) do |f|

  .form-inputs
    = f.text_field :title
    = f.text_area :body

  .form-actions
    = f.submit :submit

app/views/posts/_post.html.slim
.post.col-sm-12.fade-in
  .post-text
    h1
      .date
        =post.created_at.strftime("%B %d, %Y")
      .title
        = post.title.upcase
      .line
    .body.col-sm-12== Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {}).render(post.body)

  /.controls
  /  /= link_to 'Show', post
  /  /= link_to 'Edit', edit_post_path(post)
  /  /= link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Title
      th Body
      th
      th
      th

  tbody
    - @posts.each do |post|

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
.container
  .col-md-10
    h1 New post

    == render 'form'

    = link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path

app/views/visitors/about.html.slim
.container
  .col-sm-8.col-sm-offset-1
    .everything
      h1.hello= random_salutation
      p
        span.name-is My name is 
        strong.name  Kit Langton.
      p.flip I'm interested in Illustration, Design, Programming, and Music.
      .dialogue
        hr.bdialogue
        p
        p Yes, I know this animation is completely unneccesary.
        p But who cares about an "About page"?
        p Why are you even here?
        p Here is me blurry:
        = image_tag "my_face.jpg", height: 300, width: 200, id: "blurry-me"
        p Is that what you wanted?
        p Oh.
        p You wanted my email?
        p Sorry...
    .hide-mail
      h3 Email me?
      h1= mail_to "kit.langton@gmail.com"

app/views/visitors/index.html.slim
/#grid-container
/  = render @illustrations
/.movie
/  video#StoreVideo autoplay="autoplay" height="320" loop="loop" poster="" preload="auto" width="315"
/    source src="/assets/Comp.mp4" type="video/mp4"

.col-md-8.col-md-offset-1
  /.post.col-sm-12
  /  #grid-container
  /    = render @illustrations
  = render @posts
br